configName: sam_g55_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMG55J19
projectName: ''
settings:
  PackageFilter: csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.4.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMG_DFP\3.0.9\samg55\atdf\ATSAMG55J19.atdf
