configName: sam_g55_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../../../..
processor: ATSAMG55J19
projectName: ''
settings:
  PackageFilter: bootloader;bsp;cec173x_soteria_lib;core;crypto;csp;Devices;dev_packs;harmony-services;net;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMG_DFP\3.7.83\samg55\atdf\ATSAMG55J19.atdf
