format_version: v1.0
type: UniqueComponent
attributes: {id: crccu}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: CRCCU_BITORDER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: CRCCU_TWIDTH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
- type: ElementPosition
  attributes: {x: '641', y: '20', id: crccu}
