format_version: v1.0
type: UniqueComponent
attributes: {id: flexcom5}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: FLEXCOM5_COMMON_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: dest}
        children:
        - {type: Value, value: /peripheral/flexcom/spi/master/}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: markup}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: plib_flexcom_spi_master_common.h}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: config/sam_g55_xpro/peripheral/flexcom/spi/master/}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/flexcom_11277/templates/plib_flexcom_spi_master_common.h.ftl}
      - type: String
        attributes: {id: type}
        children:
        - {type: Value, value: HEADER}
  - type: File
    attributes: {id: FLEXCOM5_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: dest}
        children:
        - {type: Value, value: /peripheral/flexcom/spi/master/}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: markup}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: plib_flexcom5_spi_master.h}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: config/sam_g55_xpro/peripheral/flexcom/spi/master/}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/flexcom_11277/templates/plib_flexcom_spi_master.h.ftl}
      - type: String
        attributes: {id: type}
        children:
        - {type: Value, value: HEADER}
  - type: File
    attributes: {id: FLEXCOM5_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: dest}
        children:
        - {type: Value, value: /peripheral/flexcom/spi/master/}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: markup}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: plib_flexcom5_spi_master.c}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: config/sam_g55_xpro/peripheral/flexcom/spi/master/}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/flexcom_11277/templates/plib_flexcom_spi_master.c.ftl}
  - type: KeyValueSet
    attributes: {id: FLEXCOM_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Integer
    attributes: {id: FLEXCOM_SPI_BAUD_RATE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: FLEXCOM_SPI_CSR0_BAUD_RATE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '1000000'}
  - type: KeyValueSet
    attributes: {id: FLEXCOM_SPI_CSR0_BITS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '0'}
  - type: Comment
    attributes: {id: FLEXCOM_SPI_CSR0_CLOCK_MODE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: FLEXCOM_SPI_CSR0_CPOL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '0'}
  - type: Integer
    attributes: {id: FLEXCOM_SPI_CSR0_DLYBCT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: FLEXCOM_SPI_CSR0_DLYBS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: FLEXCOM_SPI_CSR0_NCPHA}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '1'}
  - type: Integer
    attributes: {id: FLEXCOM_SPI_CSR0_SCBR_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '119'}
  - type: Integer
    attributes: {id: FLEXCOM_SPI_CSR1_SCBR_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '119'}
  - type: KeyValueSet
    attributes: {id: FLEXCOM_SPI_CSR_BITS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: FLEXCOM_SPI_CSR_CPOL}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: FLEXCOM_SPI_CSR_INDEX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '0'}
  - type: KeyValueSet
    attributes: {id: FLEXCOM_SPI_CSR_NCPHA}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Hex
    attributes: {id: FLEXCOM_SPI_DUMMY_DATA}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: FLEXCOM_SPI_EN_NPCS0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: 'true'}
  - type: Boolean
    attributes: {id: FLEXCOM_SPI_EN_NPCS1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: FLEXCOM_SPI_MR_BRSRCCLK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: FLEXCOM_SPI_MR_DLYBCS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: FLEXCOM_SPI_MR_MSTR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: FLEXCOM_SPI_MR_PCS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: FLEXCOM_SPI_NUM_CSR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '1'}
  - type: Integer
    attributes: {id: FLEXCOM_SPI_PERIPHERAL_CLOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '119996416'}
  - type: File
    attributes: {id: FLEXCOM_SYS_DEF}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: markup}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_DEFINITIONS_H_INCLUDES}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/flexcom_11277/templates/system/definitions.h.ftl}
      - type: String
        attributes: {id: type}
        children:
        - {type: Value, value: STRING}
  - type: File
    attributes: {id: FLEXCOM_SYS_INIT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: markup}
        children:
        - {type: Value, value: 'true'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_INIT_C_SYS_INITIALIZE_PERIPHERALS}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/flexcom_11277/templates/system/initialization.c.ftl}
      - type: String
        attributes: {id: type}
        children:
        - {type: Value, value: STRING}
  - type: Integer
    attributes: {id: FLEXCOM_TWI_CLK_SRC_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '119996416'}
  - type: Integer
    attributes: {id: FLEXCOM_TWI_CWGR_CHDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '146'}
  - type: Integer
    attributes: {id: FLEXCOM_TWI_CWGR_CKDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '0'}
  - type: Integer
    attributes: {id: FLEXCOM_TWI_CWGR_CLDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '146'}
  - type: Integer
    attributes: {id: FLEX_USART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '119996416'}
  - type: String
    attributes: {id: RECEIVE_DATA_REGISTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '&(FLEXCOM5_REGS->FLEX_SPI_RDR)'}
  - type: Boolean
    attributes: {id: SPI_INTERRUPT_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: 'true'}
  - type: String
    attributes: {id: TRANSMIT_DATA_REGISTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: '&(FLEXCOM5_REGS->FLEX_SPI_TDR)'}
  - type: Boolean
    attributes: {id: TWI_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: flexcom5, value: 'true'}
  - type: Boolean
    attributes: {id: USE_SPI_DMA}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: FLEXCOM5_I2C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectCapability
    attributes: {id: FLEXCOM5_UART}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '30', y: '59', id: flexcom5}
