configName: sam_g55_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMG55J19
projectName: ''
settings:
  PackageFilter: aerospace;aws_cloud;bootloader;bsp;bt;core;crypto;cryptoauthlib;cryptoauthlib_apps;csp;ethercat;expresslogic_threadx;gfx;gfx_apps;micrium_ucos3;motor_control;net;touch;usb;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMG_DFP\3.2.38\samg55\atdf\ATSAMG55J19.atdf
