configName: sam_g55_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../../../..
processor: ATSAMG55J19
projectName: ''
settings:
  PackageFilter: audio;bootloader;bsp;core;core_apps_pic32cz_ca;crypto;cryptoauthlib;csp;gfx;mbed_os_rtos;mbed_os_rtos_apps;micrium_ucos3;motor_control;net;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMG_DFP\3.5.60\samg55\atdf\ATSAMG55J19.atdf
